spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/java_task
    username: andrii
    password: lmc325
    driver-class-name: org.postgresql.Driver

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: very-long-secret-key
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    com.springapp.andrii.security: DEBUG